/* Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/

var totalSum = 0;
var upperLimit = 4000000;
var firstNumber = 1;
var secondNumber = 2;

while (firstNumber < upperLimit) {
  if (secondNumber % 2 === 0) {
    totalSum += secondNumber;
  }
  var temp = firstNumber;
  firstNumber = secondNumber;
  secondNumber = temp + firstNumber;
}

console.log(totalSum);
